run_name: ddpm
seed: 42
data_dir: ./data
image_size: 32
batch_size: 128 
num_workers: 4
num_classes: 10
num_epochs: 20
learning_rate: 0.0005
weight_decay: 0.01
num_train_timesteps: 1000
num_inference_steps: 250
beta_start: 0.0001
beta_end: 0.02
beta_schedule: linear

variance_type: fixed_small
prediction_type: epsilon
unet_in_size: 32
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.1

use_cifar10: True
ckpt: /jet/home/wzhang31/hw5_student_starter_code/experiments/exp-3-ddpm/checkpoints/checkpoint_epoch_19.pth
