_wandb:
    value:
        cli_version: 0.21.2
        e:
            tw4n8upgp0u8js2an76yzt2jvcvp4v2u:
                args:
                    - --config
                    - configs/ddpm.yaml
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 40
                cpu_count_logical: 40
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "315926315008"
                        used: "80524021760"
                email: wyz2@andrew.cmu.edu
                executable: /jet/home/wzhang31/idlhw5_env/bin/python
                git:
                    commit: 844ff98f6d0c052b4b520697b5159256b5fe5713
                    remote: https://github.com/williamyzhang/idlhw5.git
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-187a76ea-faa2-65e7-c44b-3f9c7d851a73
                host: v002.ib.bridges2.psc.edu
                memory:
                    total: "540673691648"
                os: Linux-4.18.0-553.22.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /jet/home/wzhang31/hw5_student_starter_code/train.py
                python: CPython 3.10.18
                root: /jet/home/wzhang31/hw5_student_starter_code
                slurm:
                    cluster_name: bridges2
                    conf: /var/spool/slurm/d/conf-cache/slurm.conf
                    cpus_on_node: "5"
                    export_env: ALL
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: cis250019p
                    job_cpus_per_node: "5"
                    job_cpus_per_node_pack_group_0: "5"
                    job_gid: "26783"
                    job_gpus: "2"
                    job_id: "35737617"
                    job_name: Interact
                    job_nodelist: v002
                    job_num_nodes: "1"
                    job_partition: GPU-shared
                    job_qos: gpuinteract
                    job_uid: "99360"
                    job_user: wzhang31
                    jobid: "35737617"
                    launch_node_ipaddr: 10.8.11.29
                    localid: "0"
                    mpi_type: none
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: v002
                    prio_process: "0"
                    procid: "0"
                    pty_port: "42945"
                    pty_win_col: "120"
                    pty_win_row: "17"
                    script_context: prolog_task
                    srun_comm_host: 10.8.11.29
                    srun_comm_port: "33205"
                    step_id: "4294967290"
                    step_launcher_port: "33205"
                    step_nodelist: v002
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    submit_dir: /jet/home/wzhang31/hw5_student_starter_code
                    submit_host: br011.ib.bridges2.psc.edu
                    task_pid: "65666"
                    tasks_per_node: "5"
                    topology_addr: v002
                    topology_addr_pattern: node
                    working_cluster: bridges2:br003:6810:9728:109
                startedAt: "2025-10-31T18:52:16.501427Z"
                writerId: tw4n8upgp0u8js2an76yzt2jvcvp4v2u
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.2
            "8":
                - 2
            "12": 0.21.2
            "13": linux-x86_64
batch_size:
    value: 32
beta_end:
    value: "0.02"
beta_schedule:
    value: linear
beta_start:
    value: "0.0001"
cfg_guidance_scale:
    value: 2
ckpt:
    value: null
clip_sample:
    value: true
clip_sample_range:
    value: 1
config:
    value: configs/ddpm.yaml
data_dir:
    value: ./data
device:
    value: cuda
distributed:
    value: false
grad_clip:
    value: 1
image_size:
    value: 128
latent_ddpm:
    value: false
learning_rate:
    value: "0.001"
local_rank:
    value: 0
max_train_steps:
    value: 31260
mixed_precision:
    value: none
num_classes:
    value: 100
num_epochs:
    value: 20
num_inference_steps:
    value: 250
num_train_timesteps:
    value: 1000
num_workers:
    value: 4
output_dir:
    value: experiments
prediction_type:
    value: epsilon
rank:
    value: 0
run_name:
    value: exp-0-ddpm
seed:
    value: 42
total_batch_size:
    value: 32
unet_attn:
    value:
        - 2
        - 3
unet_ch:
    value: 128
unet_ch_mult:
    value:
        - 1
        - 2
        - 2
        - 4
unet_dropout:
    value: "0.1"
unet_in_ch:
    value: 3
unet_in_size:
    value: 128
unet_num_res_blocks:
    value: 2
use_cfg:
    value: false
use_cifar10:
    value: true
use_ddim:
    value: false
variance_type:
    value: fixed_small
weight_decay:
    value: "0.01"
world_size:
    value: 1
